name: Daily US Stock Monitor

on:
  schedule:
    # 北京时间 08:00，周一到周五
    - cron: "0 0 * * 1-5"

    # 北京时间 21:00，周一到周五
    - cron: "0 13 * * 1-5"

  workflow_dispatch:

jobs:
  run-stock-monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run stock monitor
        env:
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
          GITHUB_SCHEDULE: ${{ github.event.schedule }}
        run: |
          python stock_monitor.py
